### ISSUE TITLE
Ray intersecting plane at infinite number of points.

### ISSUE THREAD

**Issue by Ming-Yeung-Alfred-Meng** [karansher/computer-graphics-ray-casting#13]
If the ray intersects the plane at an infinite number of points, do we still render the plane?

**Comment by Glowies** [comment]
This is up to you. The only case where this occurs is when the ray is completely parallel to and on the plane, which will be very rare. So your result image will not look very different in either case. I would recommend not rendering it because it could get tricky to find an appropriate `t` value when you have an infinite number of intersection points.
